/**
 * Goku AI Assistant - Knowledge Base & Routing Registry
 * Contains domain knowledge, intents, synonyms, route mappings, and contextual suggestions.
 */

export const GOKU_KNOWLEDGE = {
  assistantName: 'Goku',
  title: 'AICP Virtual Guide & AI Navigator',
  welcomeGreeting: "Hello! I’m Goku, your AI assistant. How can I help you today?",
  welcomeSubtext: "Ask me to find any feature, service, or tool — or tell me what you'd like to do in natural language!",

  // Quick prompt chips displayed to the user
  quickChips: [
    { label: '💼 Find Internships', query: 'Find internships and jobs' },
    { label: '📄 ATS Resume Maker', query: 'I want to build an ATS resume' },
    { label: '🧠 AI Mock Interview', query: 'Practice an AI mock interview' },
    { label: '🎯 Skill Gap Analysis', query: 'Analyze my skill gaps' },
    { label: '🥗 Diet Plan (Demo)', query: 'I want a diet plan for weight gain' },
    { label: '🔥 Calorie Calculator', query: 'I want to know how many calories I should consume' },
    { label: '💪 Workout Plan', query: 'Give me a workout plan' },
    { label: '🩺 Health Checker', query: 'I want to check my symptoms' },
  ],

  // Comprehensive intent & navigation registry
  services: [
    // --- Specific prompts highlighted in prompt specification ---
    {
      id: 'diet-plan',
      title: 'Diet Plan Section',
      route: '/diet-plan',
      keywords: ['diet', 'diet plan', 'meal plan', 'weight gain', 'weight loss', 'nutrition', 'bulk', 'lean bulk', 'cutting', 'calories diet', 'healthy food'],
      exactMatches: [
        'i want a diet plan for weight gain',
        'i want a diet plan',
        'diet plan for weight gain',
        'diet plan for weight loss',
        'give me a diet plan',
      ],
      response: "Sure! I can help you with that. Taking you to the Weight Gain Diet Plan section.",
      guidance: "Here you can explore customized nutritional blueprints for weight gain, clean bulking, balanced energy, and macronutrient targets.",
      badge: 'Nutrition Guide',
      category: 'Health & Wellness',
    },
    {
      id: 'calorie-calculator',
      title: 'Calorie Calculator',
      route: '/calorie-calculator',
      keywords: ['calorie', 'calories', 'calculate calories', 'how many calories', 'bmr', 'tdee', 'macro intake', 'daily calories', 'energy expenditure'],
      exactMatches: [
        'i want to know how many calories i should consume',
        'how many calories should i consume',
        'calculate calories',
        'calorie calculator',
      ],
      response: "Sure! I can help you calculate your daily caloric needs. Taking you to the Calorie Calculator.",
      guidance: "Estimate your Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE) based on your metrics and goals.",
      badge: 'Energy Metrics',
      category: 'Health & Wellness',
    },
    {
      id: 'workout-plan',
      title: 'Workout Plan',
      route: '/workout-plan',
      keywords: ['workout', 'workout plan', 'exercise', 'training', 'gym', 'fitness', 'lifting', 'push pull legs', 'full body', 'muscle', 'routine'],
      exactMatches: [
        'give me a workout plan',
        'i want a workout plan',
        'workout routine',
        'gym workout plan',
      ],
      response: "Sure! Let's get your training started. Taking you to the Workout Plan section.",
      guidance: "Access tailored exercise splits, progressive overload routines, and workout schedules for all experience levels.",
      badge: 'Fitness Plan',
      category: 'Health & Wellness',
    },
    {
      id: 'health-checker',
      title: 'Health Checker',
      route: '/health-checker',
      keywords: ['symptom', 'symptoms', 'check symptoms', 'health checker', 'wellness check', 'illness', 'sick', 'health screening'],
      exactMatches: [
        'i want to check my symptoms',
        'check my symptoms',
        'symptom checker',
        'health checker',
      ],
      response: "Sure! Taking you to the Health & Symptom Checker to evaluate common indicators.",
      guidance: "Review symptom clusters, wellness indicators, and self-care recommendations.",
      badge: 'Wellness Triage',
      category: 'Health & Wellness',
    },

    // --- Core AICP Platform Features ---
    {
      id: 'resume-builder',
      title: 'ATS Resume Maker',
      route: '/resume',
      keywords: ['resume', 'cv', 'ats', 'ats resume', 'resume maker', 'resume builder', 'curriculum vitae', 'ats score', 'export pdf resume', 'resume template', 'prepare resume'],
      exactMatches: [
        'i want to prepare my resume',
        'prepare my resume',
        'prepare resume',
        'i want to build a resume',
        'create ats resume',
        'make resume',
        'ats resume maker',
      ],
      response: "Sure! Let's build your industry-ready resume. Taking you to the ATS Resume Maker.",
      guidance: "Our ATS Resume Maker formats your achievements with high-density keywords and high ATS parse rates.",
      badge: 'Career Tool',
      category: 'Career & Jobs',
    },
    {
      id: 'opportunities',
      title: 'Opportunity Radar',
      route: '/opportunities',
      keywords: ['internship', 'internships', 'job', 'jobs', 'hiring', 'vacancy', 'openings', 'find jobs', 'apply for jobs', 'match opportunities', 'roles', 'full-time', 'part-time', 'find opportunities'],
      exactMatches: [
        'i want to find opportunities',
        'find opportunities',
        'find internships',
        'search jobs',
        'explore opportunities',
      ],
      response: "Sure! Taking you to the Opportunity Radar to explore internships and jobs matched to your skills.",
      guidance: "Filter verified enterprise roles, view real-time skill-match percentages, and submit one-click applications.",
      badge: 'Talent Radar',
      category: 'Opportunities',
    },
    {
      id: 'career-agent',
      title: 'AI Career Agent Hub',
      route: '/career-agent',
      keywords: ['career agent', 'career ai', 'career advisor', 'career path', 'career guidance', 'counseling', 'mentor', 'trajectory'],
      exactMatches: [
        'open career agent',
        'ai career agent',
        'career advisor',
      ],
      response: "Sure! Taking you to the central AI Career Agent workspace.",
      guidance: "Engage with 14 specialized AI sub-agents for comprehensive career acceleration and personalized planning.",
      badge: 'Autonomous AI',
      category: 'AI Agents',
    },
    {
      id: 'mock-interview',
      title: 'AI Mock Interview',
      route: '/career-agent?tab=mock-interview',
      keywords: ['interview', 'mock interview', 'ai interview', 'practice interview', 'behavioral questions', 'technical questions', 'interview simulator', 'hr round'],
      exactMatches: [
        'i want a mock interview',
        'practice interview',
        'mock interview',
        'start interview',
        'ai mock interview',
      ],
      response: "Sure! Taking you to the AI Mock Interview simulator to sharpen your interview performance.",
      guidance: "Practice live conversational questions with immediate AI scoring, model answers, and rubric-based feedback.",
      badge: 'Interview Drill',
      category: 'Preparation',
    },
    {
      id: 'skill-gap',
      title: 'Skill Gap & Roadmap',
      route: '/career-agent?tab=skill-gap',
      keywords: ['skill gap', 'missing skills', 'skill analysis', 'knowledge gap', 'upskill', 'what skills do i need', 'target role skills'],
      exactMatches: [
        'analyze skill gaps',
        'check skill gap',
        'what skills am i missing',
      ],
      response: "Sure! Taking you to the Skill Gap Analyzer to identify missing competencies.",
      guidance: "Compare your evaluated skill profile directly against market requirements for your dream position.",
      badge: 'Skill Intelligence',
      category: 'Skills',
    },
    {
      id: 'learning-roadmap',
      title: 'Personalized Career Roadmap',
      route: '/career-agent?tab=roadmap',
      keywords: ['roadmap', 'learning roadmap', '30 day plan', '60 day plan', '90 day plan', 'milestones', 'learning schedule'],
      exactMatches: [
        'show roadmap',
        'career roadmap',
        'learning path',
      ],
      response: "Sure! Taking you to your 30/60/90-Day Learning Roadmap.",
      guidance: "Follow structured, milestone-driven roadmaps designed to turn theoretical knowledge into verified projects.",
      badge: 'Roadmaps',
      category: 'Learning',
    },
    {
      id: 'projects',
      title: 'AI Project Recommender',
      route: '/career-agent?tab=projects',
      keywords: ['project', 'projects', 'portfolio', 'project ideas', 'what should i build', 'capstone', 'github project'],
      exactMatches: [
        'recommend projects',
        'project ideas',
        'what to build',
      ],
      response: "Sure! Taking you to AI Project Recommendations to build portfolio-grade evidence.",
      guidance: "Get real-world project specifications tailored to close your specific technical skill gaps.",
      badge: 'Portfolio Boost',
      category: 'Projects',
    },
    {
      id: 'assessments',
      title: 'Assessment Center',
      route: '/assessments',
      keywords: ['assessment', 'assessments', 'test', 'tests', 'exam', 'quiz', 'coding test', 'mcq', 'skill verification', 'take test'],
      exactMatches: [
        'take assessment',
        'skill assessment',
        'test center',
      ],
      response: "Sure! Taking you to the Assessment Center to verify your capabilities.",
      guidance: "Take standardized industry mock tests and MCQs that earn verified skill badges for employers.",
      badge: 'Skill Proof',
      category: 'Assessments',
    },
    {
      id: 'applications',
      title: 'Application Tracker',
      route: '/applications',
      keywords: ['application', 'applications', 'track application', 'status', 'applied jobs', 'interview date', 'shortlisted', 'offer'],
      exactMatches: [
        'track applications',
        'my applications',
        'application status',
      ],
      response: "Sure! Taking you to your Application Tracker.",
      guidance: "Track real-time status of your applied internships and jobs through Applied, Shortlisted, Interview, and Offer stages.",
      badge: 'Status Pipeline',
      category: 'Tracking',
    },
    {
      id: 'learning-studio',
      title: 'Learning Studio',
      route: '/learning',
      keywords: ['learning', 'learning studio', 'courses', 'programs', 'study', 'certifications', 'faculty training', 'curriculum'],
      exactMatches: [
        'open learning',
        'learning programs',
        'browse courses',
      ],
      response: "Sure! Taking you to the Learning Studio to explore skill programs.",
      guidance: "Enroll in industry-aligned learning tracks and earn verified credentials recognized across the portal.",
      badge: 'Upskilling',
      category: 'Learning',
    },
    {
      id: 'collaborations',
      title: 'Collaboration Hub',
      route: '/collaborations',
      keywords: ['collaboration', 'collaborations', 'academic partner', 'research', 'fdp', 'faculty development', 'consultancy', 'joint project'],
      exactMatches: [
        'find collaborations',
        'research partnerships',
        'faculty collaborations',
      ],
      response: "Sure! Taking you to the Collaboration Hub for academic and industrial partnerships.",
      guidance: "Connect faculties with R&D departments for joint patents, sponsored consultancy, and training programs.",
      badge: 'Partnerships',
      category: 'Academia',
    },
    {
      id: 'skills',
      title: 'Skill Profile & Evidence',
      route: '/skills',
      keywords: ['skills', 'check skills', 'my skills', 'skill analysis', 'verified skills', 'skill profile', 'evaluate skills', 'check my skills'],
      exactMatches: [
        'i want to check my skills',
        'check my skills',
        'check skills',
        'my skills',
        'skill profile',
      ],
      response: "Sure! Taking you to your Skill Profile and Evaluation section.",
      guidance: "Review your verified skills, project signals, and AI readiness scores.",
      badge: 'Skill Radar',
      category: 'Skills',
    },
    {
      id: 'profile',
      title: 'Profile & Skills Editor',
      route: '/profile',
      keywords: ['profile', 'edit profile', 'my profile', 'account', 'update bio', 'education', 'skills list', 'user profile'],
      exactMatches: [
        'edit profile',
        'open profile',
        'update profile',
      ],
      response: "Sure! Taking you to your Profile Editor.",
      guidance: "Keep your skills, verified links, and academic details up to date so recommendations stay accurate.",
      badge: 'Member Profile',
      category: 'Account',
    },
    {
      id: 'analytics',
      title: 'Analytics Room',
      route: '/analytics',
      keywords: ['analytics', 'metrics', 'outcomes', 'insights', 'placement statistics', 'institutional report', 'skill trends', 'data'],
      exactMatches: [
        'view analytics',
        'analytics dashboard',
        'platform metrics',
      ],
      response: "Sure! Taking you to the Analytics Room to review performance data.",
      guidance: "Analyze student placement rates, skill demand curves, and institutional readiness indexes.",
      badge: 'Data Intelligence',
      category: 'Intelligence',
    },
    {
      id: 'dashboard',
      title: 'Workspace Dashboard',
      route: '/dashboard',
      keywords: ['dashboard', 'home workspace', 'overview', 'summary', 'main console'],
      exactMatches: [
        'go to dashboard',
        'open dashboard',
        'main dashboard',
      ],
      response: "Sure! Taking you to your primary Workspace Dashboard.",
      guidance: "View your personalized dashboard widgets, upcoming deadlines, and recommended next moves.",
      badge: 'Control Center',
      category: 'Workspace',
    },
    {
      id: 'login',
      title: 'Login Portal',
      route: '/login',
      keywords: ['login', 'sign in', 'log in', 'access account', 'otp login', 'authenticate'],
      exactMatches: [
        'i want to log in',
        'login',
        'sign in',
      ],
      response: "Taking you to the secure OTP Login page.",
      guidance: "Enter your registered email to receive an instant verification passcode.",
      badge: 'Authentication',
      category: 'Access',
    },
    {
      id: 'register',
      title: 'Role Registration',
      route: '/register',
      keywords: ['register', 'sign up', 'create account', 'join', 'new user', 'student register', 'industry register', 'academician register', 'institution register'],
      exactMatches: [
        'create account',
        'register now',
        'sign up',
      ],
      response: "Taking you to the Registration Portal to join AICP.",
      guidance: "Choose from 4 role pathways: Student, Industry Partner, Academician, or Institution.",
      badge: 'Onboarding',
      category: 'Access',
    },
    {
      id: 'manage-opportunities',
      title: 'Industry Postings Manager',
      route: '/manage-opportunities',
      keywords: ['post job', 'post internship', 'create opportunity', 'employer', 'hiring manager', 'job posting', 'publish listing'],
      exactMatches: [
        'post a job',
        'manage postings',
        'publish internship',
      ],
      response: "Taking you to the Industry Postings Manager.",
      guidance: "Draft, publish, and manage live internship and employment opportunities with required skill tags.",
      badge: 'Recruiter Suite',
      category: 'Recruitment',
    },
    {
      id: 'applicants',
      title: 'Candidate Review & Applicants',
      route: '/applicants',
      keywords: ['applicants', 'candidates', 'review applicants', 'shortlist students', 'hiring pipeline', 'applications received'],
      exactMatches: [
        'view applicants',
        'review candidates',
        'student applicants',
      ],
      response: "Taking you to the Candidate Review workspace.",
      guidance: "Review students ranked by AI skill match score, examine test evidence, and schedule interviews.",
      badge: 'Candidate Review',
      category: 'Recruitment',
    },
  ],

  // Common FAQ knowledge answers
  faqs: [
    {
      triggers: ['who are you', 'what is your name', 'tell me about yourself', 'who is goku'],
      answer: "I am Goku, your intelligent AI assistant and virtual guide! I'm integrated directly into this platform to help you navigate, understand all available features, identify the right tools for your needs, and take you wherever you need to go in seconds.",
    },
    {
      triggers: ['what is this website', 'what is aicp', 'what can this platform do', 'about platform'],
      answer: "This is AICP (Academia-Industry Collaboration Portal). It connects Students, Industry Recruiters, Academicians, and Institutions. Key capabilities include AI skill-matching, ATS resume building, AI mock interviews, learning roadmaps, and verified internships.",
    },
    {
      triggers: ['how does redirection work', 'can you navigate me', 'smart navigation', 'how to use you'],
      answer: "Simply tell me what you want to do in natural language (e.g. 'I want a diet plan', 'Find internships', or 'Build an ATS resume'). I'll recognize what you need, explain the service, and automatically guide or redirect you to that page!",
    },
    {
      triggers: ['help', 'what can i ask', 'features', 'all services'],
      answer: "You can ask me about anything! For example: \n• 'I want an ATS resume' 📄\n• 'Find me internships' 💼\n• 'Practice AI mock interview' 🧠\n• 'Check my skill gaps' 🎯\n• 'I want a diet plan for weight gain' 🥗\n• 'How many calories should I consume' 🔥\n• 'Give me a workout plan' 💪\n• 'I want to check my symptoms' 🩺",
    },
  ],
}

